//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Leaderboard
{
    public partial class LeaderboardHome
    {
        protected System.Web.UI.WebControls.Repeater rptLeaderboard;
        protected System.Web.UI.WebControls.Panel pnlEmpty;
    }
}
