//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary
{
    public partial class SiteMaster
    {
        /// <summary>
        /// SiteStylesheet control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlLink SiteStylesheet;

        /// <summary>
        /// phAdminNav control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phAdminNav;

        /// <summary>
        /// phMemberLinks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMemberLinks;

        /// <summary>
        /// phGuestActions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phGuestActions;

        /// <summary>
        /// phUserActions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phUserActions;

        /// <summary>
        /// litAvatarInitials control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAvatarInitials;

        /// <summary>
        /// litUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUserName;

        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
