//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.MasterPages
{
    public partial class AdminMaster
    {
        protected global::binary.Controls.NotificationBell NotificationBell;
        protected System.Web.UI.WebControls.ContentPlaceHolder AdminHeaderTitle;
        protected System.Web.UI.WebControls.ContentPlaceHolder AdminHeaderSubtitle;
        protected System.Web.UI.WebControls.ContentPlaceHolder AdminHeaderActions;
        protected System.Web.UI.WebControls.ContentPlaceHolder AdminMainContent;
    }
}
