//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.MasterPages
{
    public partial class SiteMaster
    {
        /// <summary>
        /// SiteStylesheet control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlLink SiteStylesheet;

        /// <summary>
        /// phSiteNavbar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phSiteNavbar;

        /// <summary>
        /// phGuestActions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phGuestActions;

        /// <summary>
        /// phUserActions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phUserActions;

        /// <summary>
        /// lnkUserPill control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkUserPill;

        /// <summary>
        /// imgAvatarNav control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgAvatarNav;

        /// <summary>
        /// litAvatarInitials control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAvatarInitials;

        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        /// <summary>
        /// phSiteFooter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phSiteFooter;

        /// <summary>
        /// lnkFooterCta control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkFooterCta;

        /// <summary>
        /// phFooterGuestLinks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phFooterGuestLinks;

        /// <summary>
        /// phFooterMemberLinks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phFooterMemberLinks;

        /// <summary>
        /// lnkFooterDashboard control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkFooterDashboard;

        /// <summary>
        /// lnkFooterProfile control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkFooterProfile;

        /// <summary>
        /// phAdminFooterNav control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phAdminFooterNav;
    }
}
