//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Auth
{
    public partial class GetStarted
    {
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Repeater rptCourses;
        protected global::System.Web.UI.WebControls.Panel pnlNoCourses;
        protected global::System.Web.UI.WebControls.Repeater rptNative;
        protected global::System.Web.UI.WebControls.Repeater rptReasons;
        protected global::System.Web.UI.WebControls.Button btnFinish;
    }
}
