//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Auth
{
    public partial class Login
    {
        /// <summary>
        /// ErrorPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ErrorPanel;

        /// <summary>
        /// litErrorMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litErrorMessage;

        /// <summary>
        /// EmailInput control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox EmailInput;

        /// <summary>
        /// rfvEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;

        /// <summary>
        /// PasswordInput control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PasswordInput;

        /// <summary>
        /// rfvPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;

        /// <summary>
        /// RememberMe control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox RememberMe;

        /// <summary>
        /// LoginBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button LoginBtn;
    }
}
