//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Auth
{
    public partial class Register
    {
        /// <summary>
        /// ErrorPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ErrorPanel;

        /// <summary>
        /// litRegisterError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRegisterError;

        /// <summary>
        /// SuccessPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel SuccessPanel;

        /// <summary>
        /// litRegisterSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRegisterSuccess;

        /// <summary>
        /// FirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox FirstName;

        /// <summary>
        /// rfvFirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFirstName;

        /// <summary>
        /// LastName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox LastName;

        /// <summary>
        /// EmailInput control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox EmailInput;

        /// <summary>
        /// rfvEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;

        /// <summary>
        /// PasswordInput control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PasswordInput;

        /// <summary>
        /// rfvPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;

        /// <summary>
        /// ConfirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox ConfirmPassword;

        /// <summary>
        /// cvPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CompareValidator cvPassword;

        /// <summary>
        /// AgreeTerms control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox AgreeTerms;

        /// <summary>
        /// RegisterBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button RegisterBtn;
    }
}
