//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Admin
{
    public partial class AdminCourses
    {
        protected System.Web.UI.WebControls.Panel pnlActionSuccess;
        protected System.Web.UI.WebControls.Literal litActionSuccess;
        protected System.Web.UI.WebControls.Panel pnlCourseError;
        protected System.Web.UI.WebControls.Literal litCourseError;
        protected System.Web.UI.WebControls.Panel pnlCourseForm;
        protected System.Web.UI.WebControls.HiddenField hfCourseId;
        protected System.Web.UI.WebControls.TextBox txtTitle;
        protected System.Web.UI.WebControls.TextBox txtDescription;
        protected System.Web.UI.WebControls.DropDownList ddlCategory;
        protected System.Web.UI.WebControls.DropDownList ddlLevel;
        protected System.Web.UI.WebControls.DropDownList ddlFlag;
        protected System.Web.UI.WebControls.FileUpload fuFlag;
        protected System.Web.UI.WebControls.TextBox txtThumbnailUrl;
        protected System.Web.UI.WebControls.CheckBox chkPublished;
        protected System.Web.UI.WebControls.Button btnSaveCourse;
        protected System.Web.UI.WebControls.Panel pnlLessons;
        protected System.Web.UI.WebControls.Panel pnlLessonError;
        protected System.Web.UI.WebControls.Literal litLessonError;
        protected System.Web.UI.WebControls.Repeater rptLessons;
        protected System.Web.UI.WebControls.HiddenField hfLessonId;
        protected System.Web.UI.WebControls.TextBox txtLessonTitle;
        protected System.Web.UI.WebControls.TextBox txtLessonContent;
        protected System.Web.UI.WebControls.Panel pnlCurrentVideo;
        protected System.Web.UI.WebControls.Literal litCurrentVideo;
        protected System.Web.UI.WebControls.CheckBox chkRemoveVideo;
        protected System.Web.UI.WebControls.TextBox txtLessonVideoUrl;
        protected System.Web.UI.WebControls.FileUpload fuLessonVideo;
        protected System.Web.UI.WebControls.TextBox txtLessonSortOrder;
        protected System.Web.UI.WebControls.Button btnSaveLesson;
        protected System.Web.UI.WebControls.DropDownList ddlCategoryFilter;
        protected System.Web.UI.WebControls.Panel pnlCourseList;
        protected System.Web.UI.WebControls.Panel pnlNoCourses;
        protected System.Web.UI.WebControls.Repeater rptCourses;
        protected System.Web.UI.WebControls.Literal litCategoryTotal;
        protected System.Web.UI.WebControls.Panel pnlCategoryError;
        protected System.Web.UI.WebControls.Literal litCategoryError;
        protected System.Web.UI.WebControls.Repeater rptCategories;
        protected System.Web.UI.WebControls.Panel pnlNoCategories;
        protected System.Web.UI.WebControls.Panel pnlAddCategory;
        protected System.Web.UI.WebControls.TextBox txtCategoryName;
        protected System.Web.UI.WebControls.Button btnAddCategory;
    }
}
