//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Admin
{
    public partial class AdminFeedback
    {
        protected System.Web.UI.WebControls.Panel pnlFeedbackError;
        protected System.Web.UI.WebControls.Literal litFeedbackError;
        protected System.Web.UI.WebControls.Panel pnlFeedbackList;
        protected System.Web.UI.WebControls.Repeater rptFeedback;
        protected System.Web.UI.WebControls.Panel pnlNoFeedback;
    }
}
