//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Admin
{
    public partial class AdminLanguages
    {
        protected System.Web.UI.WebControls.HiddenField hfLanguagesPage;
        protected System.Web.UI.WebControls.Panel pnlActionSuccess;
        protected System.Web.UI.WebControls.Literal litActionSuccess;
        protected System.Web.UI.WebControls.Panel pnlLanguageError;
        protected System.Web.UI.WebControls.Literal litLanguageError;
        protected System.Web.UI.WebControls.Panel pnlLanguageForm;
        protected System.Web.UI.WebControls.Literal litFormTitle;
        protected System.Web.UI.WebControls.HiddenField hfCategoryId;
        protected System.Web.UI.WebControls.TextBox txtLanguageName;
        protected System.Web.UI.WebControls.Button btnSaveLanguage;
        protected System.Web.UI.WebControls.Literal litTotalLanguages;
        protected System.Web.UI.WebControls.Literal litTotalCourses;
        protected System.Web.UI.WebControls.Literal litTotalLearners;
        protected System.Web.UI.WebControls.Panel pnlLanguageFilters;
        protected System.Web.UI.WebControls.TextBox txtLanguageSearch;
        protected System.Web.UI.WebControls.Button btnLanguageSearch;
        protected System.Web.UI.WebControls.Panel pnlLanguageFilterSummary;
        protected System.Web.UI.WebControls.Literal litLanguageFilterSummary;
        protected System.Web.UI.WebControls.LinkButton lnkClearLanguageFilters;
        protected System.Web.UI.WebControls.Panel pnlLanguageList;
        protected System.Web.UI.WebControls.Repeater rptLanguages;
        protected System.Web.UI.WebControls.Literal litLanguagePageInfo;
        protected System.Web.UI.WebControls.LinkButton lnkLanguagePrevPage;
        protected System.Web.UI.WebControls.LinkButton lnkLanguageNextPage;
        protected System.Web.UI.WebControls.Panel pnlNoLanguages;
    }
}
