//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Admin
{
    public partial class AdminLessonQuiz
    {
        protected global::System.Web.UI.WebControls.Literal litSubtitle;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkBack;
        protected global::System.Web.UI.WebControls.Panel pnlActionSuccess;
        protected global::System.Web.UI.WebControls.Literal litActionSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlNoQuiz;
        protected global::System.Web.UI.WebControls.Panel pnlCreate;
        protected global::System.Web.UI.WebControls.TextBox txtNewTitle;
        protected global::System.Web.UI.WebControls.Button btnCreateQuiz;
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;
        protected global::System.Web.UI.WebControls.Literal litQuestionCount;
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;
        protected global::System.Web.UI.WebControls.Panel pnlNoQuestions;
        protected global::System.Web.UI.WebControls.Panel pnlEditor;
        protected global::System.Web.UI.WebControls.Literal litEditorTitle;
        protected global::System.Web.UI.WebControls.HiddenField hfQuestionId;
        protected global::System.Web.UI.WebControls.TextBox txtQuestion;
        protected global::System.Web.UI.WebControls.TextBox txtOptionA;
        protected global::System.Web.UI.WebControls.TextBox txtOptionB;
        protected global::System.Web.UI.WebControls.TextBox txtOptionC;
        protected global::System.Web.UI.WebControls.TextBox txtOptionD;
        protected global::System.Web.UI.WebControls.Button btnSaveQuestion;
        protected global::System.Web.UI.WebControls.HyperLink lnkCancelEdit;
        protected global::System.Web.UI.WebControls.Panel pnlRename;
        protected global::System.Web.UI.WebControls.TextBox txtQuizTitle;
        protected global::System.Web.UI.WebControls.Button btnRenameQuiz;
        protected global::System.Web.UI.WebControls.Button btnDeleteQuiz;
    }
}
