//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Admin
{
    public partial class AdminReports
    {
        protected System.Web.UI.WebControls.Literal litTotalCourses;
        protected System.Web.UI.WebControls.Literal litTotalEnrollments;
        protected System.Web.UI.WebControls.Literal litQuizAttempts;
        protected System.Web.UI.WebControls.Literal litAvgScore;
        protected System.Web.UI.WebControls.Literal litPublishedCount;
        protected System.Web.UI.WebControls.Literal litDraftCount;
        protected System.Web.UI.HtmlControls.HtmlGenericControl segPublished;
        protected System.Web.UI.HtmlControls.HtmlGenericControl segDraft;
        protected System.Web.UI.WebControls.Repeater rptTopCourses;
        protected System.Web.UI.WebControls.Repeater rptActivity;
        protected System.Web.UI.WebControls.Panel pnlNoActivity;
    }
}
