//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Admin
{
    public partial class AdminUsers
    {
        protected System.Web.UI.WebControls.HiddenField hfUsersPage;
        protected System.Web.UI.WebControls.Panel pnlActionSuccess;
        protected System.Web.UI.WebControls.Literal litActionSuccess;
        protected System.Web.UI.WebControls.Panel pnlUserError;
        protected System.Web.UI.WebControls.Literal litUserError;
        protected System.Web.UI.WebControls.Panel pnlUserForm;
        protected System.Web.UI.WebControls.Literal litFormTitle;
        protected System.Web.UI.WebControls.HiddenField hfUserId;
        protected System.Web.UI.WebControls.TextBox txtFirstName;
        protected System.Web.UI.WebControls.TextBox txtLastName;
        protected System.Web.UI.WebControls.TextBox txtEmail;
        protected System.Web.UI.WebControls.Panel pnlPasswordField;
        protected System.Web.UI.WebControls.TextBox txtPassword;
        protected System.Web.UI.WebControls.DropDownList ddlRole;
        protected System.Web.UI.WebControls.CheckBox chkActive;
        protected System.Web.UI.WebControls.Literal litSelfEditNote;
        protected System.Web.UI.WebControls.Button btnSaveUser;
        protected System.Web.UI.WebControls.TextBox txtUserSearch;
        protected System.Web.UI.WebControls.DropDownList ddlRoleFilter;
        protected System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        protected System.Web.UI.WebControls.Button btnUserSearch;
        protected System.Web.UI.WebControls.Panel pnlUserList;
        protected System.Web.UI.WebControls.Repeater rptUsers;
        protected System.Web.UI.WebControls.Literal litPageInfo;
        protected System.Web.UI.WebControls.LinkButton lnkPrevPage;
        protected System.Web.UI.WebControls.LinkButton lnkNextPage;
        protected System.Web.UI.WebControls.Panel pnlNoUsers;
    }
}
