//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Pages
{
    public partial class About
    {
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkHeroSecondary;
        protected global::System.Web.UI.WebControls.Literal litStatCourses;
        protected global::System.Web.UI.WebControls.Literal litStatLessons;
        protected global::System.Web.UI.WebControls.Literal litStatFamilies;
        protected global::System.Web.UI.WebControls.Literal litStatLearners;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkCtaBottom;
    }
}
