//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Pages
{
    public partial class Contact
    {
        /// <summary>
        /// FirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox FirstName;

        /// <summary>
        /// rfvFirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFirstName;

        /// <summary>
        /// LastName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox LastName;

        /// <summary>
        /// Email control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Email;

        /// <summary>
        /// rfvEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;

        /// <summary>
        /// Subject control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList Subject;

        /// <summary>
        /// Message control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Message;

        /// <summary>
        /// rfvMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMessage;

        /// <summary>
        /// SuccessPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel SuccessPanel;

        /// <summary>
        /// SubmitBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button SubmitBtn;
    }
}
