//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Users
{
    public partial class UsersHome
    {
        protected System.Web.UI.WebControls.Repeater rptTopLearners;
        protected System.Web.UI.WebControls.Panel pnlNoLearners;
    }
}
