//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Users
{
    public partial class Profile
    {
        /// <summary>
        /// litAvatar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAvatar;

        /// <summary>
        /// litFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFullName;

        /// <summary>
        /// litEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEmail;

        /// <summary>
        /// litRoleBadge control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRoleBadge;

        /// <summary>
        /// litActiveCoursesCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litActiveCoursesCount;

        /// <summary>
        /// ProfileAlertPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ProfileAlertPanel;

        /// <summary>
        /// litProfileAlert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProfileAlert;

        /// <summary>
        /// ProfileErrorPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ProfileErrorPanel;

        /// <summary>
        /// litProfileError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProfileError;

        /// <summary>
        /// txtFirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;

        /// <summary>
        /// rfvFirst control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFirst;

        /// <summary>
        /// txtLastName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLastName;

        /// <summary>
        /// rfvLast control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLast;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// btnSaveProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;

        /// <summary>
        /// txtCurrentPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;

        /// <summary>
        /// rfvCurrent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCurrent;

        /// <summary>
        /// txtNewPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;

        /// <summary>
        /// rfvNew control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNew;

        /// <summary>
        /// txtConfirmNewPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtConfirmNewPassword;

        /// <summary>
        /// cvNewPass control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CompareValidator cvNewPass;

        /// <summary>
        /// btnChangePassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnChangePassword;
    }
}
