//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Users
{
    public partial class Profile
    {
        /// <summary>
        /// imgAvatarSidebar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgAvatarSidebar;

        /// <summary>
        /// litAvatar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAvatar;

        /// <summary>
        /// NotificationBell control.
        /// </summary>
        protected global::binary.Controls.NotificationBell NotificationBell;

        /// <summary>
        /// imgAvatarHeader control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgAvatarHeader;

        /// <summary>
        /// litHeaderAvatar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeaderAvatar;

        /// <summary>
        /// litFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFullName;

        /// <summary>
        /// litActiveCoursesCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litActiveCoursesCount;

        /// <summary>
        /// litTotalXp control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalXp;

        /// <summary>
        /// litRank control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRank;

        /// <summary>
        /// litCompletedLessonsCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCompletedLessonsCount;

        /// <summary>
        /// litLearnerLevel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLearnerLevel;

        /// <summary>
        /// hfActiveTab control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfActiveTab;

        /// <summary>
        /// litStreak control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStreak;

        /// <summary>
        /// rptActivityChart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptActivityChart;

        /// <summary>
        /// pnlQuizList control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlQuizList;

        /// <summary>
        /// rptQuizzes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptQuizzes;

        /// <summary>
        /// pnlNoQuizzes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoQuizzes;

        /// <summary>
        /// rptAttempts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptAttempts;

        /// <summary>
        /// pnlNoAttempts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoAttempts;

        /// <summary>
        /// pnlQuizPlay control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlQuizPlay;

        /// <summary>
        /// litPlayQuizTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPlayQuizTitle;

        /// <summary>
        /// hfPlayQuizId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfPlayQuizId;

        /// <summary>
        /// rptQuestions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;

        /// <summary>
        /// btnSubmitQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSubmitQuiz;

        /// <summary>
        /// lnkCancelQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkCancelQuiz;

        /// <summary>
        /// pnlQuizResult control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlQuizResult;

        /// <summary>
        /// litResultEmoji control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litResultEmoji;

        /// <summary>
        /// litResultScore control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litResultScore;

        /// <summary>
        /// litResultMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litResultMessage;

        /// <summary>
        /// litResultXp control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litResultXp;

        /// <summary>
        /// lnkRetryQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkRetryQuiz;

        /// <summary>
        /// lnkBackToList control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkBackToList;

        /// <summary>
        /// rptEnrollments control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptEnrollments;

        /// <summary>
        /// pnlNoEnrollments control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoEnrollments;

        /// <summary>
        /// ProfileAlertPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ProfileAlertPanel;

        /// <summary>
        /// litProfileAlert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProfileAlert;

        /// <summary>
        /// ProfileErrorPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ProfileErrorPanel;

        /// <summary>
        /// litProfileError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProfileError;

        /// <summary>
        /// imgAvatarPreview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgAvatarPreview;

        /// <summary>
        /// litAvatarPreview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAvatarPreview;

        /// <summary>
        /// fuAvatar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fuAvatar;

        /// <summary>
        /// litProfileName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProfileName;

        /// <summary>
        /// litProfileEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProfileEmail;

        /// <summary>
        /// litMemberSince control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMemberSince;

        /// <summary>
        /// litProfileTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProfileTitle;

        /// <summary>
        /// litProfileTitleHint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProfileTitleHint;

        /// <summary>
        /// litExpTitleEmoji control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litExpTitleEmoji;

        /// <summary>
        /// litExpTitleName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litExpTitleName;

        /// <summary>
        /// litExpTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litExpTotal;

        /// <summary>
        /// litExpToNext control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litExpToNext;

        /// <summary>
        /// expProgressBar control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl expProgressBar;

        /// <summary>
        /// rptTitles control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptTitles;

        /// <summary>
        /// txtFirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;

        /// <summary>
        /// rfvFirst control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFirst;

        /// <summary>
        /// txtLastName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLastName;

        /// <summary>
        /// rfvLast control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLast;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// btnSaveProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;

        /// <summary>
        /// txtCurrentPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;

        /// <summary>
        /// rfvCurrent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCurrent;

        /// <summary>
        /// txtNewPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;

        /// <summary>
        /// rfvNew control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNew;

        /// <summary>
        /// txtConfirmNewPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtConfirmNewPassword;

        /// <summary>
        /// cvNewPass control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CompareValidator cvNewPass;

        /// <summary>
        /// btnChangePassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnChangePassword;

        /// <summary>
        /// litContinueCourse control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litContinueCourse;

        /// <summary>
        /// litContinueLesson control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litContinueLesson;

        /// <summary>
        /// litCountCompleted control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCountCompleted;

        /// <summary>
        /// litCountInProgress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCountInProgress;

        /// <summary>
        /// litCountNotStarted control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCountNotStarted;

        /// <summary>
        /// litGreetingName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litGreetingName;

        /// <summary>
        /// litGreetingTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litGreetingTitle;

        /// <summary>
        /// litInProgressBadge control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litInProgressBadge;

        /// <summary>
        /// litLessonsThisWeek control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLessonsThisWeek;

        /// <summary>
        /// litLessonsThisWeekBadge control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLessonsThisWeekBadge;

        /// <summary>
        /// lnkContinue control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkContinue;

        /// <summary>
        /// pnlContinue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlContinue;

        /// <summary>
        /// pnlStartLearning control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlStartLearning;

        /// <summary>
        /// segCompleted control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl segCompleted;

        /// <summary>
        /// segInProgress control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl segInProgress;

        /// <summary>
        /// segNotStarted control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl segNotStarted;
    }
}
