//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Controls
{
    public partial class NotificationBell
    {
        /// <summary>
        /// phUnreadDot control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phUnreadDot;

        /// <summary>
        /// litUnreadLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUnreadLabel;

        /// <summary>
        /// rptInbox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptInbox;

        /// <summary>
        /// rptArchived control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptArchived;
    }
}
