//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary.Courses
{
    public partial class Detail
    {
        protected System.Web.UI.HtmlControls.HtmlGenericControl badgeLevel;
        protected System.Web.UI.HtmlControls.HtmlGenericControl badgeCategory;
        protected System.Web.UI.WebControls.Literal litTitle;
        protected System.Web.UI.WebControls.Literal litDescription;
        protected System.Web.UI.WebControls.Literal litLessonCount;
        protected System.Web.UI.WebControls.Panel pnlEnrollError;
        protected System.Web.UI.WebControls.Literal litEnrollError;
        protected System.Web.UI.WebControls.Panel pnlEnrollSuccess;
        protected System.Web.UI.WebControls.Literal litEnrollSuccess;
        protected System.Web.UI.WebControls.HiddenField hfCourseId;
        protected System.Web.UI.WebControls.Panel pnlGuestCta;
        protected System.Web.UI.HtmlControls.HtmlAnchor lnkSignInEnroll;
        protected System.Web.UI.HtmlControls.HtmlAnchor lnkRegisterEnroll;
        protected System.Web.UI.WebControls.Panel pnlEnrollCta;
        protected System.Web.UI.WebControls.Button btnEnroll;
        protected System.Web.UI.WebControls.Panel pnlEnrolled;
        protected System.Web.UI.WebControls.Literal litProgressPercent;
        protected System.Web.UI.HtmlControls.HtmlGenericControl progressBarFill;
        protected System.Web.UI.WebControls.Panel pnlAdminPreview;
        protected System.Web.UI.WebControls.Panel pnlSyllabus;
        protected System.Web.UI.WebControls.Literal litSyllabusHint;
        protected System.Web.UI.WebControls.Repeater rptLessons;
    }
}
